artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  #source_URL: "https://datasets-server.huggingface.co/rows?dataset=cfilt%2Fiitb-english-hindi&config=default&split=train&offset=0&length=100"
  local_data_file: artifacts/data_ingestion/iitb-english-hindi
  #unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["train", "test", "validation"]


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/iitb-english-hindi
  tokenizer_name: Helsinki-NLP/opus-mt-en-hi


model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation/iitb-english-hindi_dataset
  model_ckpt: Helsinki-NLP/opus-mt-en-hi
  

model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_transformation/iitb-english-hindi_dataset
  model_path: artifacts/model_trainer/opus-en-hi-model
  tokenizer_path: artifacts/model_trainer/tokenizer
  metric_file_name: artifacts/model_evaluation/metrics.csv